# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/TCL/constraints/ZYBO_Master.xdc

# Block Designs: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/drone.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone || ORIG_REF_NAME==drone}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_dvi2rgb_0_0/drone_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_dvi2rgb_0_0 || ORIG_REF_NAME==drone_dvi2rgb_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_processing_system7_0_0/drone_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_0 || ORIG_REF_NAME==drone_processing_system7_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xlconcat_0_0/drone_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xlconcat_0_0 || ORIG_REF_NAME==drone_xlconcat_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xlconstant_0_0/drone_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xlconstant_0_0 || ORIG_REF_NAME==drone_xlconstant_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xlconstant_1_0/drone_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xlconstant_1_0 || ORIG_REF_NAME==drone_xlconstant_1_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_RC_1_0/drone_RC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_RC_1_0 || ORIG_REF_NAME==drone_RC_1_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_RC_0_0/drone_RC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_RC_0_0 || ORIG_REF_NAME==drone_RC_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_gpio_video_0 || ORIG_REF_NAME==drone_axi_gpio_video_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_mem_intercon_0/drone_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_mem_intercon_0 || ORIG_REF_NAME==drone_axi_mem_intercon_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_vdma_0_0 || ORIG_REF_NAME==drone_axi_vdma_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_proc_sys_reset_0_0 || ORIG_REF_NAME==drone_proc_sys_reset_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_processing_system7_0_axi_periph_0/drone_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==drone_processing_system7_0_axi_periph_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_150M_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_vid_in_axi4s_0_0/drone_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==drone_v_vid_in_axi4s_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_dma_0_0 || ORIG_REF_NAME==drone_axi_dma_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_fifo_generator_0_0 || ORIG_REF_NAME==drone_fifo_generator_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M1_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M1_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_G_0/drone_G_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_G_0 || ORIG_REF_NAME==drone_G_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_R_0/drone_R_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_R_0 || ORIG_REF_NAME==drone_R_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_B_0/drone_B_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_B_0 || ORIG_REF_NAME==drone_B_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xlconcat_1_0/drone_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xlconcat_1_0 || ORIG_REF_NAME==drone_xlconcat_1_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_tc_0_0/drone_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_v_tc_0_0 || ORIG_REF_NAME==drone_v_tc_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_DVBOutputBuffer_0_0/drone_DVBOutputBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_DVBOutputBuffer_0_0 || ORIG_REF_NAME==drone_DVBOutputBuffer_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_kill_switch_0_0/drone_kill_switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_kill_switch_0_0 || ORIG_REF_NAME==drone_kill_switch_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_PWM_AXI_triple_0_0/drone_PWM_AXI_triple_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_0_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_PWM_AXI_triple_3_0/drone_PWM_AXI_triple_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_3_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_3_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_PWM_AXI_triple_4_0/drone_PWM_AXI_triple_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_4_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_4_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_PWM_AXI_triple_5_0/drone_PWM_AXI_triple_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_5_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_5_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Control_0_0/drone_ModemS2Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_ModemS2Control_0_0 || ORIG_REF_NAME==drone_ModemS2Control_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/drone_ModemS2Zybo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_ModemS2Zybo_0_0 || ORIG_REF_NAME==drone_ModemS2Zybo_0_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/cic_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_compiler_0_1 || ORIG_REF_NAME==cic_compiler_0_1}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/fir_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0_1 || ORIG_REF_NAME==fir_compiler_0_1}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_0/drone_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xbar_0 || ORIG_REF_NAME==drone_xbar_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_1/drone_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xbar_1 || ORIG_REF_NAME==drone_xbar_1}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s00_regslice_0/drone_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_s00_regslice_0 || ORIG_REF_NAME==drone_s00_regslice_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s01_regslice_0/drone_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_s01_regslice_0 || ORIG_REF_NAME==drone_s01_regslice_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_data_fifo_0/drone_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_m00_data_fifo_0 || ORIG_REF_NAME==drone_m00_data_fifo_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_regslice_0/drone_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_m00_regslice_0 || ORIG_REF_NAME==drone_m00_regslice_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_0/drone_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_0 || ORIG_REF_NAME==drone_auto_pc_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_df_0/drone_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_us_df_0 || ORIG_REF_NAME==drone_auto_us_df_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_cc_df_0/drone_auto_us_cc_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_us_cc_df_0 || ORIG_REF_NAME==drone_auto_us_cc_df_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_0/drone_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_us_0 || ORIG_REF_NAME==drone_auto_us_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_0/drone_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_cc_0 || ORIG_REF_NAME==drone_auto_cc_0}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_1/drone_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_cc_1 || ORIG_REF_NAME==drone_auto_cc_1}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_2/drone_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_cc_2 || ORIG_REF_NAME==drone_auto_cc_2}]

# IP: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_1/drone_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_1 || ORIG_REF_NAME==drone_auto_pc_1}]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_dvi2rgb_0_0 || ORIG_REF_NAME==drone_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_processing_system7_0_0/drone_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_0 || ORIG_REF_NAME==drone_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_video_0 || ORIG_REF_NAME==drone_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_video_0 || ORIG_REF_NAME==drone_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_vdma_0_0 || ORIG_REF_NAME==drone_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_vdma_0_0 || ORIG_REF_NAME==drone_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_proc_sys_reset_0_0 || ORIG_REF_NAME==drone_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_proc_sys_reset_0_0 || ORIG_REF_NAME==drone_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_150M_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_vid_in_axi4s_0_0/drone_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==drone_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_vid_in_axi4s_0_0/drone_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_dma_0_0 || ORIG_REF_NAME==drone_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_dma_0_0 || ORIG_REF_NAME==drone_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0/drone_fifo_generator_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_fifo_generator_0_0 || ORIG_REF_NAME==drone_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0/drone_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_fifo_generator_0_0 || ORIG_REF_NAME==drone_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M1_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M1_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M1_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M1_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_tc_0_0/drone_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_v_tc_0_0 || ORIG_REF_NAME==drone_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_tc_0_0/drone_v_tc_0_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0_1 || ORIG_REF_NAME==fir_compiler_0_1}] {/U0 }]/U0 ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_0/drone_xbar_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_1/drone_xbar_1_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s00_regslice_0/drone_s00_regslice_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s01_regslice_0/drone_s01_regslice_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_data_fifo_0/drone_m00_data_fifo_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_regslice_0/drone_m00_regslice_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_0/drone_auto_pc_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_df_0/drone_auto_us_df_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_df_0/drone_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_us_df_0 || ORIG_REF_NAME==drone_auto_us_df_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_cc_df_0/drone_auto_us_cc_df_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_cc_df_0/drone_auto_us_cc_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_us_cc_df_0 || ORIG_REF_NAME==drone_auto_us_cc_df_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_0/drone_auto_us_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_0/drone_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_us_0 || ORIG_REF_NAME==drone_auto_us_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_0/drone_auto_cc_0_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_0/drone_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_cc_0 || ORIG_REF_NAME==drone_auto_cc_0}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_1/drone_auto_cc_1_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_1/drone_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_cc_1 || ORIG_REF_NAME==drone_auto_cc_1}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_2/drone_auto_cc_2_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_2/drone_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_auto_cc_2 || ORIG_REF_NAME==drone_auto_cc_2}] {/inst }]/inst ]]

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_1/drone_auto_pc_1_ooc.xdc

# XDC: /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/drone_ooc.xdc
