# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/students/data/eagle4/Drone_files/Drone_Files/HW/drone/drone.cache/wt [current_project]
set_property parent.project_path /users/students/data/eagle4/Drone_files/Drone_Files/HW/drone/drone.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /users/students/data/eagle4/Drone_files/Drone_Files/HW/TCL/IP_Repo [current_project]
add_files /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/rrc.coe
add_files /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/drone.bd
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_processing_system7_0_0/drone_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_gpio_video_0/drone_axi_gpio_video_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_vdma_0_0/drone_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_proc_sys_reset_0_0/drone_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_150M_0/drone_rst_processing_system7_0_150M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_vid_in_axi4s_0_0/drone_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_vid_in_axi4s_0_0/drone_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_axi_dma_0_0/drone_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0/drone_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0/drone_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_fifo_generator_0_0/drone_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_rst_processing_system7_0_100M1_0/drone_rst_processing_system7_0_100M1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_tc_0_0/drone_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_v_tc_0_0/drone_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_0/drone_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_xbar_1/drone_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s00_regslice_0/drone_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_s01_regslice_0/drone_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_data_fifo_0/drone_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_m00_regslice_0/drone_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_0/drone_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_df_0/drone_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_df_0/drone_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_cc_df_0/drone_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_cc_df_0/drone_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_0/drone_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_us_0/drone_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_0/drone_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_0/drone_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_1/drone_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_1/drone_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_2/drone_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_cc_2/drone_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/ip/drone_auto_pc_1/drone_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/drone_ooc.xdc]
set_property is_locked true [get_files /users/students/data/eagle4/Drone_files/Drone_Files/HW/BD/drone.bd]

read_vhdl -library xil_defaultlib /users/students/data/eagle4/Drone_files/Drone_Files/HW/TCL/hdl/drone_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /users/students/data/eagle4/Drone_files/Drone_Files/HW/TCL/constraints/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /users/students/data/eagle4/Drone_files/Drone_Files/HW/TCL/constraints/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top drone_wrapper -part xc7z010clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -retiming -fsm_extraction off -keep_equivalent_registers


write_checkpoint -force -noxdef drone_wrapper.dcp

catch { report_utilization -file drone_wrapper_utilization_synth.rpt -pb drone_wrapper_utilization_synth.pb }
