
--- WARNING: THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT ---

library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity cell_mapper_rom_dvbt2 is
port(
    codeType: in integer range 0 to 2;
    modType: in integer range 0 to 3;
    blockSize: in integer range 0 to 1;
    lut_bitIndex: in integer range 0 to 15;
    lut_bitPermutedIndex: out integer range 0 to 15;
    cell_groupedByTwo: out std_logic
);
end cell_mapper_rom_dvbt2;

architecture cell_mapper_rom_arch_dvbt2 of cell_mapper_rom_dvbt2 is
begin

    romProc: process(codeType, modType, blockSize, lut_bitIndex)
    begin
        lut_bitPermutedIndex <= 0;
        cell_groupedByTwo <= '0';

        if(codeType = 0) then
            if (modType = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 5;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 11;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 6;
                    when 5 => lut_bitPermutedIndex <= 2;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 1;
                    when 9 => lut_bitPermutedIndex <= 8;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 15;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 13;
                    when 3 => lut_bitPermutedIndex <= 3;
                    when 4 => lut_bitPermutedIndex <= 8;
                    when 5 => lut_bitPermutedIndex <= 11;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 10;
                    when 9 => lut_bitPermutedIndex <= 6;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when 11 => lut_bitPermutedIndex <= 7;
                    when 12 => lut_bitPermutedIndex <= 12;
                    when 13 => lut_bitPermutedIndex <= 2;
                    when 14 => lut_bitPermutedIndex <= 14;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 5;
                    when 4 => lut_bitPermutedIndex <= 2;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
        end if;
        if(codeType = 1) then
            if (modType = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 5;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 7;
                    when 6 => lut_bitPermutedIndex <= 3;
                    when 7 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 5;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 2;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 6;
                    when 3 => lut_bitPermutedIndex <= 9;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 1;
                    when 7 => lut_bitPermutedIndex <= 8;
                    when 8 => lut_bitPermutedIndex <= 4;
                    when 9 => lut_bitPermutedIndex <= 11;
                    when 10 => lut_bitPermutedIndex <= 5;
                    when 11 => lut_bitPermutedIndex <= 10;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 11;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 6;
                    when 5 => lut_bitPermutedIndex <= 2;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 1;
                    when 9 => lut_bitPermutedIndex <= 8;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 2;
                    when 1 => lut_bitPermutedIndex <= 11;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 9;
                    when 6 => lut_bitPermutedIndex <= 1;
                    when 7 => lut_bitPermutedIndex <= 8;
                    when 8 => lut_bitPermutedIndex <= 10;
                    when 9 => lut_bitPermutedIndex <= 13;
                    when 10 => lut_bitPermutedIndex <= 7;
                    when 11 => lut_bitPermutedIndex <= 14;
                    when 12 => lut_bitPermutedIndex <= 6;
                    when 13 => lut_bitPermutedIndex <= 15;
                    when 14 => lut_bitPermutedIndex <= 5;
                    when 15 => lut_bitPermutedIndex <= 12;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 5;
                    when 4 => lut_bitPermutedIndex <= 2;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
        end if;
        if(codeType = 2) then
            if (modType = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 5;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 11;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 6;
                    when 5 => lut_bitPermutedIndex <= 2;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 1;
                    when 9 => lut_bitPermutedIndex <= 8;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 2;
                    when 2 => lut_bitPermutedIndex <= 9;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 13;
                    when 7 => lut_bitPermutedIndex <= 3;
                    when 8 => lut_bitPermutedIndex <= 14;
                    when 9 => lut_bitPermutedIndex <= 10;
                    when 10 => lut_bitPermutedIndex <= 15;
                    when 11 => lut_bitPermutedIndex <= 5;
                    when 12 => lut_bitPermutedIndex <= 8;
                    when 13 => lut_bitPermutedIndex <= 12;
                    when 14 => lut_bitPermutedIndex <= 11;
                    when 15 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 5;
                    when 4 => lut_bitPermutedIndex <= 2;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
        end if;
    

    end process;

end cell_mapper_rom_arch_dvbt2;

--- WARNING: THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT ---

library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity cell_mapper_rom_dvbc2 is
port(
    codeType: in integer range 0 to 2;
    modType: in integer range 0 to 5;
    blockSize: in integer range 0 to 1;
    lut_bitIndex: in integer range 0 to 23;
    lut_bitPermutedIndex: out integer range 0 to 23;
    cell_groupedByTwo: out std_logic
);
end cell_mapper_rom_dvbc2;

architecture cell_mapper_rom_arch_dvbc2 of cell_mapper_rom_dvbc2 is
begin

    romProc: process(codeType, modType, blockSize, lut_bitIndex)
    begin
        lut_bitPermutedIndex <= 0;
        cell_groupedByTwo <= '0';

        if(codeType = 0) then
            if (modType = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 5;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 11;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 6;
                    when 5 => lut_bitPermutedIndex <= 2;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 1;
                    when 9 => lut_bitPermutedIndex <= 8;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 15;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 13;
                    when 3 => lut_bitPermutedIndex <= 3;
                    when 4 => lut_bitPermutedIndex <= 8;
                    when 5 => lut_bitPermutedIndex <= 11;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 10;
                    when 9 => lut_bitPermutedIndex <= 6;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when 11 => lut_bitPermutedIndex <= 7;
                    when 12 => lut_bitPermutedIndex <= 12;
                    when 13 => lut_bitPermutedIndex <= 2;
                    when 14 => lut_bitPermutedIndex <= 14;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 5;
                    when 4 => lut_bitPermutedIndex <= 2;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 4 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 1 => lut_bitPermutedIndex <= 16;
                    when 2 => lut_bitPermutedIndex <= 7;
                    when 3 => lut_bitPermutedIndex <= 19;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 15;
                    when 6 => lut_bitPermutedIndex <= 3;
                    when 7 => lut_bitPermutedIndex <= 12;
                    when 9 => lut_bitPermutedIndex <= 11;
                    when 10 => lut_bitPermutedIndex <= 10;
                    when 11 => lut_bitPermutedIndex <= 9;
                    when 12 => lut_bitPermutedIndex <= 13;
                    when 13 => lut_bitPermutedIndex <= 2;
                    when 14 => lut_bitPermutedIndex <= 14;
                    when 15 => lut_bitPermutedIndex <= 5;
                    when 16 => lut_bitPermutedIndex <= 17;
                    when 17 => lut_bitPermutedIndex <= 6;
                    when 18 => lut_bitPermutedIndex <= 18;
                    when 19 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 4 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 7;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 19;
                    when 5 => lut_bitPermutedIndex <= 4;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 17;
                    when 9 => lut_bitPermutedIndex <= 6;
                    when 10 => lut_bitPermutedIndex <= 14;
                    when 11 => lut_bitPermutedIndex <= 11;
                    when 12 => lut_bitPermutedIndex <= 2;
                    when 13 => lut_bitPermutedIndex <= 18;
                    when 14 => lut_bitPermutedIndex <= 16;
                    when 15 => lut_bitPermutedIndex <= 15;
                    when 17 => lut_bitPermutedIndex <= 1;
                    when 18 => lut_bitPermutedIndex <= 13;
                    when 19 => lut_bitPermutedIndex <= 12;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 5 and blockSize = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 2 => lut_bitPermutedIndex <= 6;
                    when 3 => lut_bitPermutedIndex <= 1;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 5;
                    when 6 => lut_bitPermutedIndex <= 2;
                    when 7 => lut_bitPermutedIndex <= 3;
                    when 8 => lut_bitPermutedIndex <= 7;
                    when 9 => lut_bitPermutedIndex <= 10;
                    when 10 => lut_bitPermutedIndex <= 11;
                    when 11 => lut_bitPermutedIndex <= 9;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 5 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 10;
                    when 1 => lut_bitPermutedIndex <= 15;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 19;
                    when 4 => lut_bitPermutedIndex <= 21;
                    when 5 => lut_bitPermutedIndex <= 16;
                    when 6 => lut_bitPermutedIndex <= 23;
                    when 7 => lut_bitPermutedIndex <= 18;
                    when 8 => lut_bitPermutedIndex <= 11;
                    when 9 => lut_bitPermutedIndex <= 14;
                    when 10 => lut_bitPermutedIndex <= 22;
                    when 11 => lut_bitPermutedIndex <= 5;
                    when 12 => lut_bitPermutedIndex <= 6;
                    when 13 => lut_bitPermutedIndex <= 17;
                    when 14 => lut_bitPermutedIndex <= 13;
                    when 15 => lut_bitPermutedIndex <= 20;
                    when 16 => lut_bitPermutedIndex <= 1;
                    when 17 => lut_bitPermutedIndex <= 3;
                    when 18 => lut_bitPermutedIndex <= 9;
                    when 19 => lut_bitPermutedIndex <= 2;
                    when 20 => lut_bitPermutedIndex <= 7;
                    when 21 => lut_bitPermutedIndex <= 8;
                    when 22 => lut_bitPermutedIndex <= 12;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
        end if;
        if(codeType = 2) then
            if (modType = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 1 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 1;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 2;
                    when 4 => lut_bitPermutedIndex <= 5;
                    when 5 => lut_bitPermutedIndex <= 3;
                    when 6 => lut_bitPermutedIndex <= 6;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 2) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 11;
                    when 1 => lut_bitPermutedIndex <= 7;
                    when 2 => lut_bitPermutedIndex <= 3;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 6;
                    when 5 => lut_bitPermutedIndex <= 2;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 1;
                    when 9 => lut_bitPermutedIndex <= 8;
                    when 10 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 2;
                    when 2 => lut_bitPermutedIndex <= 9;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 13;
                    when 7 => lut_bitPermutedIndex <= 3;
                    when 8 => lut_bitPermutedIndex <= 14;
                    when 9 => lut_bitPermutedIndex <= 10;
                    when 10 => lut_bitPermutedIndex <= 15;
                    when 11 => lut_bitPermutedIndex <= 5;
                    when 12 => lut_bitPermutedIndex <= 8;
                    when 13 => lut_bitPermutedIndex <= 12;
                    when 14 => lut_bitPermutedIndex <= 11;
                    when 15 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 3 and blockSize = 1) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 7;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 1;
                    when 3 => lut_bitPermutedIndex <= 5;
                    when 4 => lut_bitPermutedIndex <= 2;
                    when 5 => lut_bitPermutedIndex <= 6;
                    when 6 => lut_bitPermutedIndex <= 4;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 4 and blockSize = 0) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 1 => lut_bitPermutedIndex <= 16;
                    when 2 => lut_bitPermutedIndex <= 7;
                    when 3 => lut_bitPermutedIndex <= 19;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 15;
                    when 6 => lut_bitPermutedIndex <= 3;
                    when 7 => lut_bitPermutedIndex <= 12;
                    when 9 => lut_bitPermutedIndex <= 11;
                    when 10 => lut_bitPermutedIndex <= 10;
                    when 11 => lut_bitPermutedIndex <= 9;
                    when 12 => lut_bitPermutedIndex <= 13;
                    when 13 => lut_bitPermutedIndex <= 2;
                    when 14 => lut_bitPermutedIndex <= 14;
                    when 15 => lut_bitPermutedIndex <= 5;
                    when 16 => lut_bitPermutedIndex <= 17;
                    when 17 => lut_bitPermutedIndex <= 6;
                    when 18 => lut_bitPermutedIndex <= 18;
                    when 19 => lut_bitPermutedIndex <= 1;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 4 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 1 => lut_bitPermutedIndex <= 3;
                    when 2 => lut_bitPermutedIndex <= 7;
                    when 3 => lut_bitPermutedIndex <= 10;
                    when 4 => lut_bitPermutedIndex <= 19;
                    when 5 => lut_bitPermutedIndex <= 4;
                    when 6 => lut_bitPermutedIndex <= 9;
                    when 7 => lut_bitPermutedIndex <= 5;
                    when 8 => lut_bitPermutedIndex <= 17;
                    when 9 => lut_bitPermutedIndex <= 6;
                    when 10 => lut_bitPermutedIndex <= 14;
                    when 11 => lut_bitPermutedIndex <= 11;
                    when 12 => lut_bitPermutedIndex <= 2;
                    when 13 => lut_bitPermutedIndex <= 18;
                    when 14 => lut_bitPermutedIndex <= 16;
                    when 15 => lut_bitPermutedIndex <= 15;
                    when 17 => lut_bitPermutedIndex <= 1;
                    when 18 => lut_bitPermutedIndex <= 13;
                    when 19 => lut_bitPermutedIndex <= 12;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 5 and blockSize = 0) then
                cell_groupedByTwo <= '0';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 8;
                    when 2 => lut_bitPermutedIndex <= 6;
                    when 3 => lut_bitPermutedIndex <= 1;
                    when 4 => lut_bitPermutedIndex <= 4;
                    when 5 => lut_bitPermutedIndex <= 5;
                    when 6 => lut_bitPermutedIndex <= 2;
                    when 7 => lut_bitPermutedIndex <= 3;
                    when 8 => lut_bitPermutedIndex <= 7;
                    when 9 => lut_bitPermutedIndex <= 10;
                    when 10 => lut_bitPermutedIndex <= 11;
                    when 11 => lut_bitPermutedIndex <= 9;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
            if (modType = 5 and blockSize = 1) then
                cell_groupedByTwo <= '1';
                case lut_bitIndex is
                    when 0 => lut_bitPermutedIndex <= 10;
                    when 1 => lut_bitPermutedIndex <= 15;
                    when 2 => lut_bitPermutedIndex <= 4;
                    when 3 => lut_bitPermutedIndex <= 19;
                    when 4 => lut_bitPermutedIndex <= 21;
                    when 5 => lut_bitPermutedIndex <= 16;
                    when 6 => lut_bitPermutedIndex <= 23;
                    when 7 => lut_bitPermutedIndex <= 18;
                    when 8 => lut_bitPermutedIndex <= 11;
                    when 9 => lut_bitPermutedIndex <= 14;
                    when 10 => lut_bitPermutedIndex <= 22;
                    when 11 => lut_bitPermutedIndex <= 5;
                    when 12 => lut_bitPermutedIndex <= 6;
                    when 13 => lut_bitPermutedIndex <= 17;
                    when 14 => lut_bitPermutedIndex <= 13;
                    when 15 => lut_bitPermutedIndex <= 20;
                    when 16 => lut_bitPermutedIndex <= 1;
                    when 17 => lut_bitPermutedIndex <= 3;
                    when 18 => lut_bitPermutedIndex <= 9;
                    when 19 => lut_bitPermutedIndex <= 2;
                    when 20 => lut_bitPermutedIndex <= 7;
                    when 21 => lut_bitPermutedIndex <= 8;
                    when 22 => lut_bitPermutedIndex <= 12;
                    when others => lut_bitPermutedIndex <= 0;
                end case;
            end if;
        end if;
    

    end process;

end cell_mapper_rom_arch_dvbc2;


--- WARNING: THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT ---

library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;

entity cell_mapper_rom_dvbs2 is
port(
    codeType: in integer range 0 to 2;
    modType: in integer range 0 to 3;
    blockSize: in integer range 0 to 1;
    lut_bitIndex: in integer range 0 to 4;
    lut_bitPermutedIndex: out integer range 0 to 4;
    cell_groupedByTwo: out std_logic
);
end cell_mapper_rom_dvbs2;

architecture cell_mapper_rom_arch_dvbs2 of cell_mapper_rom_dvbs2 is
begin

    cell_groupedByTwo <= '0';

    romProc: process(codeType, modType, blockSize, lut_bitIndex)
    begin
        -- In the S2 case bits are not permuted, unless when using 8PSK (modType=1) and rate 3/5 (codeType=1) with 64k fecframe
        lut_bitPermutedIndex <= lut_bitIndex;

        if(modType = 1 and codeType=1 and blockSize=0) then
            if(lut_bitIndex=0) then
                lut_bitPermutedIndex <= 2;
            elsif(lut_bitIndex=2) then
                lut_bitPermutedIndex <= 0;
            end if;
        end if;
    end process;

end cell_mapper_rom_arch_dvbs2;




