# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.cache/wt [current_project]
set_property parent.project_path /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ARM_1.bd
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_processing_system7_0_0/ARM_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_0_0/ARM_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_0_0/ARM_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_0_0/ARM_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_1_0/ARM_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_1_0/ARM_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_axi_gpio_1_0/ARM_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_rst_processing_system7_0_100M_0/ARM_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_rst_processing_system7_0_100M_0/ARM_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_rst_processing_system7_0_100M_0/ARM_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_xbar_0/ARM_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ip/ARM_1_auto_pc_0/ARM_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ARM_1_ooc.xdc]
set_property is_locked true [get_files /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/ARM_1.bd]

read_verilog -library xil_defaultlib /users/students/data/eagle4/project_Attitude_Controller/project_Attitude_Controller.srcs/sources_1/bd/ARM_1/hdl/ARM_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ARM_1_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef ARM_1_wrapper.dcp

catch { report_utilization -file ARM_1_wrapper_utilization_synth.rpt -pb ARM_1_wrapper_utilization_synth.pb }
