# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/montgomery_sw_project/montgomery_sw_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project || ORIG_REF_NAME==montgomery_sw_project}]

# IP: bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project_axi_gpio_0_0 || ORIG_REF_NAME==montgomery_sw_project_axi_gpio_0_0}]

# IP: bd/montgomery_sw_project/ip/montgomery_sw_project_processing_system7_0_0/montgomery_sw_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project_processing_system7_0_0 || ORIG_REF_NAME==montgomery_sw_project_processing_system7_0_0}]

# IP: bd/montgomery_sw_project/ip/montgomery_sw_project_processing_system7_0_axi_periph_0/montgomery_sw_project_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==montgomery_sw_project_processing_system7_0_axi_periph_0}]

# IP: bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0}]

# IP: bd/montgomery_sw_project/ip/montgomery_sw_project_auto_pc_0/montgomery_sw_project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==montgomery_sw_project_auto_pc_0 || ORIG_REF_NAME==montgomery_sw_project_auto_pc_0}]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==montgomery_sw_project_axi_gpio_0_0 || ORIG_REF_NAME==montgomery_sw_project_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0_ooc.xdc

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==montgomery_sw_project_axi_gpio_0_0 || ORIG_REF_NAME==montgomery_sw_project_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_processing_system7_0_0/montgomery_sw_project_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==montgomery_sw_project_processing_system7_0_0 || ORIG_REF_NAME==montgomery_sw_project_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==montgomery_sw_project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/montgomery_sw_project/ip/montgomery_sw_project_auto_pc_0/montgomery_sw_project_auto_pc_0_ooc.xdc

# XDC: bd/montgomery_sw_project/montgomery_sw_project_ooc.xdc
