# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.cache/wt [current_project]
set_property parent.project_path /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/src/ip_repo
  /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/src/ip_repo
} [current_project]
add_files /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/montgomery_sw_project.bd
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_axi_gpio_0_0/montgomery_sw_project_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_processing_system7_0_0/montgomery_sw_project_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_rst_processing_system7_0_100M_0/montgomery_sw_project_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/ip/montgomery_sw_project_auto_pc_0/montgomery_sw_project_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/montgomery_sw_project_ooc.xdc]
set_property is_locked true [get_files /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/bd/montgomery_sw_project/montgomery_sw_project.bd]

read_verilog -library xil_defaultlib /users/start2015/r0486429/Documents/DDP/exsession1/ddp_sw/montgomery_sw_project/montgomery_sw_project.srcs/sources_1/imports/hdl/montgomery_sw_project_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top montgomery_sw_project_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef montgomery_sw_project_wrapper.dcp

catch { report_utilization -file montgomery_sw_project_wrapper_utilization_synth.rpt -pb montgomery_sw_project_wrapper_utilization_synth.pb }
