#!/bin/bash -f
# Vivado (TM) v2016.2 (64-bit)
#
# Filename    : drone.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Mar 12 15:11:24 CET 2018
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016 
#
# usage: drone.sh [-help]
# usage: drone.sh [-lib_map_path]
# usage: drone.sh [-noclean_files]
# usage: drone.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'drone.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-load "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/lib/lnx64.o/libxil_vcs.so:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm processing_system7_bfm_v2_0_5 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_11 lib_pkg_v1_0_2 fifo_generator_v13_1_1 lib_fifo_v1_0_5 blk_mem_gen_v8_3_3 lib_bmg_v1_0_5 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_11 axi_vdma_v6_2_8 proc_sys_reset_v5_0_9 fifo_generator_v13_0_3 v_vid_in_axi4s_v4_0_3 axi_sg_v4_1_3 axi_dma_v7_1_10 v_tc_v6_1_8 xbip_utils_v3_0_6 axi_utils_v2_0_2 cic_compiler_v4_0_10 fir_compiler_v7_2_6 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_9 axi_data_fifo_v2_1_8 axi_crossbar_v2_1_10 axi_protocol_converter_v2_1_9 axi_clock_converter_v2_1_8 axi_dwidth_converter_v2_1_9)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "drone.sh - Script generated by export_simulation (Vivado v2016.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/esat/micas-data/software/xilinx_vivado_2016.2/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/SyncBase.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/SyncAsync.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/InputSERDES.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/ChannelBond.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/src/dvi2rgb.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_dvi2rgb_0_0/sim/drone_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_wr.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_rd.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_wr_4.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_rd_4.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_hp2_3.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_arb_hp0_1.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_ssw_hp.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_sparse_mem.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_reg_map.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_ocm_mem.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_intr_wr_mem.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_intr_rd_mem.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_fmsw_gp.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_regc.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_ocmc.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_interconnect_model.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_gen_reset.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_gen_clock.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_ddrc.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_axi_slave.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_axi_master.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_afi_slave.v" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl/processing_system7_bfm_v2_0_processing_system7_bfm.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/sim/drone_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_xlconcat_0_0/work/xlconcat.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_xlconcat_0_0/sim/drone_xlconcat_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_xlconstant_0_0/work/xlconstant.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_xlconstant_0_0/sim/drone_xlconstant_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_xlconstant_1_0/sim/drone_xlconstant_1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_RC_1_0/src/PWM_measure.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_RC_1_0/hdl/RC_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_RC_1_0/hdl/RC_v1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_RC_1_0/sim/drone_RC_1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_RC_0_0/sim/drone_RC_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_lite_ipif_v3_0_4/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_lite_ipif_v3_0_4/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_lite_ipif_v3_0_4/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_lite_ipif_v3_0_4/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_lite_ipif_v3_0_4/hdl/src/vhdl/axi_lite_ipif.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/interrupt_control_v3_1_4/hdl/src/vhdl/interrupt_control.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_11 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_gpio_v2_0_11/hdl/src/vhdl/gpio_core.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/axi_gpio_v2_0_11/hdl/src/vhdl/axi_gpio.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_testpins_0/sim/drone_axi_gpio_testpins_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_led_0/sim/drone_axi_gpio_led_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_gpio_video_0/sim/drone_axi_gpio_video_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_pkg_v1_0_2/hdl/src/vhdl/lib_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_1 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_fifo_v1_0_5/hdl/src/vhdl/async_fifo_fg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_fifo_v1_0_5/hdl/src/vhdl/sync_fifo_fg.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_bmg_v1_0_5/hdl/src/vhdl/blk_mem_gen_wrapper.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/dynshreg_f.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/lib_srl_fifo_v1_0_2/hdl/src/vhdl/srl_fifo_f.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_11 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_reset.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_afifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_sfifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_fifo.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_cmd_status.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_scc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_strb_gen2.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_pcc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_addr_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_rdmux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_rddata_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_rd_status_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_wr_demux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_wrdata_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_wr_status_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_skid2mm_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_skid_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_rd_sf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_wr_sf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_stbs_set.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_stbs_set_nodre.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_ibttcc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_indet_btt.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_dre_mux2_1_x_n.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_dre_mux4_1_x_n.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_dre_mux8_1_x_n.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_mm2s_dre.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_dre.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_ms_strb_set.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_mssai_skid_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_slice.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_scatter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_realign.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_basic_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_omit_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_s2mm_full_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_mm2s_basic_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_mm2s_omit_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover_mm2s_full_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_datamover_v5_1_11/hdl/src/vhdl/axi_datamover.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_2_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_infrastructure_v1_0_util_axis2vector.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_infrastructure_v1_0_util_vector2axis.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_register_slice_v1_0_axisc_register_slice.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_register_slice_v1_0_axis_register_slice.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axisc_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axisc_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog/axi_vdma_v6_2_axis_dwidth_converter_v1_0_axis_dwidth_converter.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_2_8 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_pkg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_pntr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_afifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_queue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_noqueue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_ftch_q_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_queue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_noqueue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_updt_q_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg_intrpt.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_sg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_pkg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_cdc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vid_cdc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sg_cdc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_reset.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_rst_module.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_lite_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_register.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_regdirect.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_reg_mux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_reg_module.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_reg_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_intrpt.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sof_gen.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_skid_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sfifo.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sfifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_afifo_builtin.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_afifo.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_afifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_mm2s_linebuf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_s2mm_linebuf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_blkmem.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_fsync_gen.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vregister.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vregister_64.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sgregister.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vaddrreg_mux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vaddrreg_mux_64.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vidreg_module.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_vidreg_module_64.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_genlock_mux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_greycoder.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_genlock_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sg_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_sts_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_mngr_64.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_mm2s_axis_dwidth_converter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma_s2mm_axis_dwidth_converter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/vhdl/axi_vdma.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/sim/drone_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_9 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_proc_sys_reset_0_0/proc_sys_reset_v5_0_9/hdl/src/vhdl/proc_sys_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_proc_sys_reset_0_0/sim/drone_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_rst_processing_system7_0_100M_0/sim/drone_rst_processing_system7_0_100M_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_rst_processing_system7_0_150M_0/sim/drone_rst_processing_system7_0_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fifo_generator_v13_0_3 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/fifo_generator_v13_0_3/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/fifo_generator_v13_0_3/hdl/fifo_generator_v13_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/v_vid_in_axi4s_v4_0_3/hdl/verilog/v_vid_in_axi4s_v4_0_coupler.v" \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/v_vid_in_axi4s_v4_0_3/hdl/verilog/v_vid_in_axi4s_v4_0_formatter.v" \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/v_vid_in_axi4s_v4_0_3/hdl/verilog/v_vid_in_axi4s_v4_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_v_vid_in_axi4s_0_0/sim/drone_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_sg_v4_1_3 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_pkg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_reset.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_sfifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_afifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_fifo.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_cmd_status.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_rdmux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_addr_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_rddata_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_rd_status_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_scc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_wr_demux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_scc_wr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_skid2mm_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_wrdata_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_wr_status_cntl.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_skid_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_mm2s_basic_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_s2mm_basic_wrap.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_datamover.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_pntr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_cntrl_strm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_queue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_noqueue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_ftch_q_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_queue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_noqueue.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_updt_q_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg_intrpt.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_sg_v4_1_3/hdl/src/vhdl/axi_sg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_10 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_pkg.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_reset.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_rst_module.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_lite_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_register.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_register_s2mm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_reg_module.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_skid_buf.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_afifo_autord.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_sofeof_gen.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_smple_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_sg_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_sts_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_cntrl_strm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_mm2s_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_sg_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_sm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_cmdsts_if.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_sts_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_sts_strm.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_s2mm_mngr.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma_cmd_split.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/axi_dma_v7_1_10/hdl/src/vhdl/axi_dma.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_axi_dma_0_0/sim/drone_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_fifo_generator_0_0/sim/drone_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_rst_processing_system7_0_100M1_0/sim/drone_rst_processing_system7_0_100M1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_G_0/work/xlslice.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_G_0/sim/drone_G_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_R_0/sim/drone_R_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_B_0/sim/drone_B_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_xlconcat_1_0/sim/drone_xlconcat_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_8 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_v_tc_0_0/v_tc_v6_1_8/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_v_tc_0_0/sim/drone_v_tc_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_DVBOutputBuffer_0_0/sim/drone_DVBOutputBuffer_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_kill_switch_0_0/kill_switch.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_kill_switch_0_0/sim/drone_kill_switch_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_0_0/hdl/PWM_AXI.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_0_0/hdl/PWM_AXI_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_0_0/hdl/PWM_AXI_v1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_0_0/sim/drone_PWM_AXI_triple_0_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_3_0/sim/drone_PWM_AXI_triple_3_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_4_0/sim/drone_PWM_AXI_triple_4_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_PWM_AXI_triple_5_0/sim/drone_PWM_AXI_triple_5_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Control_0_0/hdl/ModemS2Control_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Control_0_0/hdl/ModemS2Control_v1_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Control_0_0/sim/drone_ModemS2Control_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/xbip_utils_v3_0_6/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/axi_utils_v2_0_2/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cic_compiler_v4_0_10 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/cic_compiler_v4_0_10/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/cic_compiler_v4_0_10/hdl/cic_compiler_v4_0.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/cic_compiler_0_1/sim/cic_compiler_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_6 $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/fir_compiler_v7_2_6/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/fir_compiler_v7_2_6/hdl/fir_compiler_v7_2.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/ip/fir_compiler_0_1/sim/fir_compiler_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/functions.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/config.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/sampleType.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/ldpc_blockXOR.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/infer_ramSinglePort.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/infer_ramDualPort.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/scrambler.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/pls.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/ldpc.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/inserter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/dvbs2_symbol_rom.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/dvb-all.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/crc8_data.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/crc8_bbh.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/cell_mapper_rom.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/byte_splitter.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/bitinterleave_coeff_rom.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/bitinterleave.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/bit2cell.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/bch.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/bbscrambler.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/BBHeader_9_byte.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/symbol_mapper.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/mpeg_sync.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/inputprocessing.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/framer.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/fec.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/tx.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/mpeg_mux.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/imports/src/tx_wrapperZybo.vhd" \
    "$ref_dir/../../../../../BD/ip/drone_ModemS2Zybo_0_0/sim/drone_ModemS2Zybo_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/generic_baseblocks_v2_1_0/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_register_slice_v2_1_9/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_register_slice_v2_1_9/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_data_fifo_v2_1_8/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_crossbar_v2_1_10/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_0/sim/drone_xbar_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_xbar_1/sim/drone_xbar_1.v" \
    "$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/sim/drone_s00_regslice_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/sim/drone_s01_regslice_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_m00_data_fifo_0/sim/drone_m00_data_fifo_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/sim/drone_m00_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_protocol_converter_v2_1_9/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_0/sim/drone_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_clock_converter_v2_1_8/hdl/verilog/axi_clock_converter_v2_1_axic_sync_clock_converter.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_clock_converter_v2_1_8/hdl/verilog/axi_clock_converter_v2_1_axic_sample_cycle_ratio.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_clock_converter_v2_1_8/hdl/verilog/axi_clock_converter_v2_1_axi_clock_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_a_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_r_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_w_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_axi_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_downsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_a_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer_pktfifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer_pktfifo.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_axi_upsizer.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_dwidth_converter_v2_1_9/hdl/verilog/axi_dwidth_converter_v2_1_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../BD/ip/drone_axi_vdma_0_0/axi_vdma_v6_2_8/hdl/src/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_processing_system7_0_0/processing_system7_bfm_v2_0_5/hdl" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_pc_1/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_m00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s00_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_s01_regslice_0/axi_infrastructure_v1_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../../BD/ip/drone_xbar_1/axi_infrastructure_v1_1_0/hdl/verilog" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_df_0/sim/drone_auto_us_df_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_cc_df_0/sim/drone_auto_us_cc_df_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_us_0/sim/drone_auto_us_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_cc_0/sim/drone_auto_cc_0.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_cc_1/sim/drone_auto_cc_1.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_cc_2/sim/drone_auto_cc_2.v" \
    "$ref_dir/../../../../../BD/ip/drone_auto_pc_1/sim/drone_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../BD/hdl/drone.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.drone xil_defaultlib.glbl -o drone_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./drone_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./drone.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key drone_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc drone_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./drone.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: drone.sh [-help]\n\
Usage: drone.sh [-lib_map_path]\n\
Usage: drone.sh [-reset_run]\n\
Usage: drone.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
